### ISSUE TITLE
Create bioconda package

### ISSUE THREAD

**Issue by johnlees** [seqan/seqan3#1168]
As requested in #1121, this is an issue to track progress on adding seqan3 to bioconda. This would mean bioconda users can include a seqan3 dependency in their conda recipes, rather than needing to use git submodules.

It's my understanding that seqan3 is a header only library, so I think the package would consist of copying the relevant files to the conda `include/` directory, plus any others that need to be installed.
A couple of test cases should be compiled to check for success.

There is currently a package for an old version which can probably just be updated.
`meta.yaml`:
```
{% set name = "SeqAn" %}
{% set version = "2.4.0" %}
{% set sha256 = "870dee2d758853a322dd561eb584fe66ddf6981e126c303c7c81c95e5495f153" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://packages.seqan.de/seqan-library/seqan-library-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - test -e ${PREFIX}/include/seqan/align.h
    - test -e ${PREFIX}/share/cmake/seqan/seqan-config.cmake
    - test -e ${PREFIX}/share/pkgconfig/seqan-2.pc

about:
  home: http://www.seqan.de/
  license: BSD-3-Clause
  summary: 'SeqAn is an open source C++ library of efficient algorithms and data structures for the analysis of sequences with the focus on biological data.'
```

`build.sh`:
```
#!/bin/bash

mkdir -p $PREFIX/include
mkdir -p $PREFIX/share/cmake
mkdir -p $PREFIX/share/doc
mkdir -p $PREFIX/share/pkgconfig
mv include/seqan $PREFIX/include
mv share/cmake/seqan $PREFIX/share/cmake
mv share/doc/seqan $PREFIX/share/doc
mv share/pkgconfig/* $PREFIX/share/pkgconfig
```

Although the conda compiler is GCC 7.3.0, the c++ libraries are >v9, so it should support the C++17 features seqan3 needs. I have previously gotten this to work on some test cases.

**Comment by marehr** [comment]
Can you give me an example how to build the `meta.yml` with bioconda?

**Comment by johnlees** [comment]
If you put your `meta.yml` and `build.sh` in a folder, say `seqan3/`, you would run
```
conda build seqan3
```

Though, with a fresh conda install/environment, you will first want to install `conda build` itself:
```
conda install conda-build
```
and set up your channels to include bioconda:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
Documentation for conda build is here: https://conda.io/projects/conda-build/en/latest/user-guide/index.html

If you have a proposed update for the `meta.yml` and `build.sh` that work locally, I am happy to submit the pull request to bioconda (which will test it on their machines, which are sometimes a bit more fussy).

Here is the `meta.yml` I would suggest:
```
{% set name = "SeqAn3" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/seqan/{{ name|lower }}/releases/download/{{ version }}/seqan-3.0.0-with-submodules.tar.gz
  sha256: ba8f0fd5d19289f95823235b69fdc5a12aba3578292463eecf750722e8662bd3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -e ${PREFIX}/include/seqan/align.h
    - test -e ${PREFIX}/share/cmake/seqan/seqan-config.cmake
    - test -e ${PREFIX}/share/pkgconfig/seqan-2.pc

about:
  home: http://docs.seqan.de/seqan/3-master-user/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'SeqAn3 is the new version of the popular SeqAn template library for the analysis of biological sequences.'
```
